import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { ReduxProvider } from "./redux/provider/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Header />
          <div className="container  mx-auto  mt-24 md:mt-18">{children}</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
